import 'package:databreeze/src/utils/plurals.dart';
import 'package:test/test.dart';

Future<void> main() async {
  final singularToPluralMap = <String, String>{
    'ability': 'abilities',
    'addendum': 'addenda',
    'address': 'addresses',
    'adulthood': 'adulthood',
    'advice': 'advice',
    'agency': 'agencies',
    'agenda': 'agenda',
    'aid': 'aid',
    'aircraft': 'aircraft',
    'alcohol': 'alcohol',
    'alga': 'algae',
    'alias': 'aliases',
    'alumna': 'alumnae',
    'alumnus': 'alumni',
    'ammo': 'ammo',
    'analysis': 'analyses',
    'analytics': 'analytics',
    'anime': 'anime',
    'apparatus': 'apparatuses',
    'appendix': 'appendices',
    'archive': 'archives',
    'athletics': 'athletics',
    'audio': 'audio',
    'axis': 'axes',
    'bacterium': 'bacteria',
    'basis': 'bases',
    'bias': 'biases',
    'bison': 'bison',
    'blitz': 'blitzes',
    'blood': 'blood',
    'bookie': 'bookies',
    'box': 'boxes',
    'bream': 'bream',
    'buffalo': 'buffaloes',
    'bus': 'buses',
    'butter': 'butter',
    'buzz': 'buzzes',
    'cache': 'caches',
    'cactus': 'cacti',
    'cafe': 'cafes',
    'campus': 'campuses',
    'carp': 'carp',
    'case': 'cases',
    'cash': 'cash',
    'category': 'categories',
    'chairman': 'chairmen',
    'chassis': 'chassis',
    'chess': 'chess',
    'child': 'children',
    'clothing': 'clothing',
    'cod': 'cod',
    'comment': 'comments',
    'commerce': 'commerce',
    'cookie': 'cookies',
    'cooperation': 'cooperation',
    'corn': 'corn',
    'corps': 'corps',
    'crisis': 'crises',
    'criterion': 'criteria',
    'curriculum': 'curricula',
    'database': 'databases',
    'datum': 'data',
    'day': 'days',
    'debris': 'debris',
    'deer': 'deer',
    'diabetes': 'diabetes',
    'diagnosis': 'diagnoses',
    'die': 'dice',
    'digestion': 'digestion',
    'dwarf': 'dwarves',
    'echo': 'echoes',
    'edge': 'edges',
    'elf': 'elves',
    'elk': 'elk',
    'ellipsis': 'ellipses',
    'embargo': 'embargoes',
    'emphasis': 'emphases',
    'energy': 'energy',
    'equipment': 'equipment',
    'ex': 'exes',
    'excretion': 'excretion',
    'experience': 'experiences',
    'expertise': 'expertise',
    'firmware': 'firmware',
    'fish': 'fish',
    'fix': 'fixes',
    'flounder': 'flounder',
    'focus': 'foci',
    'foobar': 'foobars',
    'foot': 'feet',
    'freshman': 'freshmen',
    'fun': 'fun',
    'fungus': 'fungi',
    'fuse': 'fuses',
    'gallows': 'gallows',
    'garbage': 'garbage',
    'glove': 'gloves',
    'goose': 'geese',
    'graffiti': 'graffiti',
    'grass': 'grass',
    'hair': 'hair',
    'half': 'halves',
    'hardware': 'hardware',
    'she': 'they',
    'headquarters': 'headquarters',
    'health': 'health',
    'hero': 'heroes',
    'herpes': 'herpes',
    'highjinks': 'highjinks',
    'themself': 'themselves',
    'hippopotamus': 'hippopotamuses',
    'homework': 'homework',
    'hoof': 'hooves',
    'horse': 'horses',
    'house': 'houses',
    'housework': 'housework',
    'human': 'humans',
    'i': 'we',
    'index': 'indices',
    'information': 'information',
    'iris': 'irises',
    'is': 'are',
    'jeans': 'jeans',
    'justice': 'justice',
    'kudos': 'kudos',
    'labour': 'labour',
    'larva': 'larvae',
    'leaf': 'leaves',
    'literature': 'literature',
    'loaf': 'loaves',
    'louse': 'lice',
    'luggage': 'luggage',
    'machinery': 'machinery',
    'mackerel': 'mackerel',
    'mail': 'mail',
    'man': 'men',
    'manga': 'manga',
    'matrix': 'matrices',
    'me': 'us',
    'means': 'means',
    'medium': 'media',
    'mews': 'mews',
    'milk': 'milk',
    'millennium': 'millennia',
    'moose': 'moose',
    'mosquito': 'mosquitoes',
    'mouse': 'mice',
    'move': 'moves',
    'movie': 'movies',
    'mud': 'mud',
    'music': 'music',
    'myself': 'ourselves',
    'neurosis': 'neuroses',
    'news': 'news',
    'newsletter': 'newsletters',
    'nucleus': 'nuclei',
    'oasis': 'oases',
    'octopus': 'octopuses',
    'offspring': 'offspring',
    'only': 'only',
    'ox': 'oxen',
    'paralysis': 'paralyses',
    'person': 'people',
    'personnel': 'personnel',
    'perspective': 'perspectives',
    'phenomenon': 'phenomena',
    'photo': 'photos',
    'pike': 'pike',
    'plankton': 'plankton',
    'pliers': 'pliers',
    'police': 'police',
    'pollution': 'pollution',
    'portfolio': 'portfolios',
    'potato': 'potatoes',
    'premises': 'premises',
    'prize': 'prizes',
    'process': 'processes',
    'query': 'queries',
    'quiz': 'quizzes',
    'radius': 'radii',
    'rain': 'rain',
    'research': 'research',
    'rice': 'rice',
    'rookie': 'rookies',
    'roomie': 'roomies',
    'safe': 'safes',
    'salesperson': 'salespeople',
    'salmon': 'salmon',
    'save': 'saves',
    'scissors': 'scissors',
    'search': 'searches',
    'semen': 'semen',
    'seraph': 'seraphim',
    'series': 'series',
    'sewage': 'sewage',
    'shambles': 'shambles',
    'sheep': 'sheep',
    'shoe': 'shoes',
    'shrimp': 'shrimp',
    'smoothie': 'smoothies',
    'software': 'software',
    'someone': 'someone',
    'species': 'species',
    'sperm': 'sperm',
    'spokesman': 'spokesmen',
    'stack': 'stacks',
    'staff': 'staff',
    'status_code': 'status_codes',
    'status': 'statuses',
    'stimulus': 'stimuli',
    'swine': 'swine',
    'switch': 'switches',
    'syllabus': 'syllabi',
    'tennis': 'tennis',
    'testis': 'testes',
    'that': 'those',
    'thief': 'thieves',
    'this': 'these',
    'tomato': 'tomatoes',
    'tooth': 'teeth',
    'torpedo': 'torpedoes',
    'traffic': 'traffic',
    'training': 'training',
    'transportation': 'transportation',
    'trellis': 'trellises',
    'trout': 'trout',
    'tuna': 'tuna',
    'vertebra': 'vertebrae',
    'vertex': 'vertices',
    'veto': 'vetoes',
    'virus': 'viruses',
    'volcano': 'volcanoes',
    'walrus': 'walruses',
    'waltz': 'waltzes',
    'water': 'water',
    'waters': 'waters',
    'wave': 'waves',
    'wealth': 'wealth',
    'welfare': 'welfare',
    'which': 'which',
    'whiting': 'whiting',
    'who': 'who',
    'wife': 'wives',
    'wildebeest': 'wildebeest',
    'wildlife': 'wildlife',
    'wish': 'wishes',
    'wolf': 'wolves',
    'woman': 'women',
    'you': 'you',
    'yourself': 'yourselves',
    'zombie': 'zombies',
  };

  group('Custom test', () {
    test('bias -> biases', () {
      final actual = Plurals.pluralize('bias');
      expect(actual, 'biases');
    });

    test('salespeople -> salesperson', () {
      final actual = Plurals.singularize('salespeople');
      expect(actual, 'salesperson');
    });
  }, skip: true);

  group('Pluralize', () {
    for (final MapEntry(key: singular, value: plural) in singularToPluralMap.entries) {
      test('Plural "$singular"', () {
        final actual = Plurals.pluralize(singular);
        expect(actual, plural);
      });
    }
  });

  group('Singularize', () {
    for (final MapEntry(key: singular, value: plural) in singularToPluralMap.entries) {
      test('Singular "$plural"', () {
        final actual = Plurals.singularize(plural);
        expect(actual, singular);
      });
    }
  });

  group('Table\'s perspective transformations', () {
    test('ClassName to collection_name', () {
      final actual = Plurals.classNameToCollectionName('ArticleTag');
      expect(actual, 'article_tags');
    });

    test('Foreign key based on collection_name', () {
      final actual = '${Plurals.singularize('customers')}_id';
      expect(actual, 'customer_id');
    });
  });
}
