targets:
  $default:
    builders:
      databreeze_generator:
        enabled: true
        generate_for:
          include:
            - models/**/*.dart

builders:
  databreeze_gen:
    import: "package:databreeze_generator/builder.dart"
    builder_factories: ["breezeModelBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    # To copy the `.g.part` content into `.g.dart` in the source tree
    applies_builders: ["source_gen:combining_builder"]
